
import java.sql.*;
import Project.Connectionprovider;
import javax.swing.JOptionPane;

public class newstudent extends javax.swing.JFrame {
    public void clear()
    {
     jTextField1.setText("");
     jTextField2.setText("");
     jTextField3.setText("");
     jTextField5.setText("");
     jTextField6.setText("");
     jTextField8.setText("");
     jComboBox1.removeAllItems();
     roomNumber();
     
    }
public void roomNumber(){
    int i=0;
    try {
        Connection con=Connectionprovider.getCon();
          Statement st =con.createStatement();
          ResultSet rs =st.executeQuery("SELECT * FROM room WHERE activate='yes' and roomstatus='Not Booked'");
          while(rs.next())
          {
              i=1;
              jComboBox1.addItem(rs.getString(1));
          }
              if(i==0)
              {
                  jButton2.setVisible(false);
                  JOptionPane.showMessageDialog(null, "All rooms are already Booked");
                  setVisible(false);
              }
          }
        
    catch (Exception e) {
        
    }
}
    
    public newstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(0, 51, 102));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NEW  STUDENT");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 90));

        panel1.setBackground(new java.awt.Color(248, 255, 232));
        panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel1ComponentShown(evt);
            }
        });
        panel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Permanant Address ");
        panel1.add(jLabel6);
        jLabel6.setBounds(50, 180, 125, 10);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("E mail Address ");
        panel1.add(jLabel5);
        jLabel5.setBounds(50, 140, 125, 10);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panel1.add(jTextField3);
        jTextField3.setBounds(270, 90, 400, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel1.add(jTextField1);
        jTextField1.setBounds(270, 10, 400, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panel1.add(jTextField2);
        jTextField2.setBounds(270, 50, 400, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mobile Number");
        panel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 125, 10);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3);
        jButton3.setBounds(570, 283, 100, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2);
        jButton2.setBounds(260, 280, 83, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Room Number");
        panel1.add(jLabel9);
        jLabel9.setBounds(50, 260, 125, 10);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panel1.add(jTextField5);
        jTextField5.setBounds(270, 132, 400, 30);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel1.add(jTextField6);
        jTextField6.setBounds(270, 170, 400, 30);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panel1.add(jTextField8);
        jTextField8.setBounds(270, 213, 400, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");
        panel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 125, 10);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Father Name");
        panel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 125, 10);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panel1.add(jComboBox1);
        jComboBox1.setBounds(270, 250, 400, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("National Identity Number");
        panel1.add(jLabel8);
        jLabel8.setBounds(50, 220, 170, 10);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Close button
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible(false);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void panel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1ComponentShown
// LABEL EVENT OR FORM COMPONENT
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        roomNumber();
    }//GEN-LAST:event_formComponentShown
// SAVE BUTTON
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mobilenum=jTextField1.getText();
        String name=jTextField2.getText();
        String fathername=jTextField3.getText();
        String email=jTextField5.getText();
        String permanentadd=jTextField6.getText();
        String nic=jTextField8.getText();
        String roomnumber=(String)jComboBox1.getSelectedItem();
        String status="living";
        
        try {
            Connection con=Connectionprovider.getCon();             // remianging from here 
            PreparedStatement ps=con.prepareStatement("INSERT INTO student VALUES(?,?,?,?,?,?,?,?)");
            ps.setString(1, mobilenum);
            ps.setString(2, name);
            ps.setString(3, fathername);
            ps.setString(4, email);
            ps.setString(5, permanentadd);
            ps.setString(6, nic);
            ps.setString(7, roomnumber);
            ps.setString(8, status);
            ps.executeUpdate();
            
            
            PreparedStatement ps1= con.prepareStatement( "UPDATE room set roomstatus='Booked' WHERE number=?");
            ps1.setString(1,roomnumber);
            ps1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//CLEAR METHOD
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
